Just sync everything. State is totally broken, scripts are real half-assed and untested, likely don't work at all. General direction is promising, and things are in the middle of being renamed.

diff --git a/charts/dev-container-workflow/scripts/volumes b/charts/dev-container-workflow/scripts/volumes
--- a/charts/dev-container-workflow/scripts/volumes
+++ b/charts/dev-container-workflow/scripts/volumes
@@ -1,44 +1,50 @@
 #!/bin/sh
-# Depends on git
 
 # Validate volumes
-if ! [[ -w $HOME_VOLUME ]]; then
-    echo "ERROR: Home persistence volume not writable. Unable to configure user applications!"; exit 1
+if ! [[ -w $HOME ]]; then
+    echo "ERROR: Home persistence volume not writable. Unable to configure user applications!"
+    exit 1
 fi
-AWS=1
+aws=1
 if ! [[ -d $AWS_VOLUME ]]; then
-    echo "WARN: AWS configuration volume not present. Unable to configure AWS CLI."; AWS=0
+    echo "WARN: AWS configuration volume not present. Unable to configure AWS CLI."
+    aws=0
 fi
-GIT=1
+git=1
 if ! [[ -d $GIT_VOLUME ]]; then
-    echo "WARN: GIT configuration volume not present. Unable to configure Git CLI."; GIT=0
+    echo "WARN: GIT configuration volume not present. Unable to configure Git CLI."
+    git=0
 fi
-SSH=1
+ssh=1
 if ! [[ -d $SSH_VOLUME ]]; then
-    echo "WARN: SSH configuration volume not present. Unable to configure SSH client and authorized_users."; SSH=0
-fi
-
-# Create user home directory if it does not exist
-if ! [[ -d $HOME ]]; then
-    mkdir $HOME
+    echo "WARN: SSH configuration volume not present. Unable to configure SSH client and authorized_users."
+   ssh=0
 fi
 
 # Symlink configuration volumes
-if ! [[ -L $HOME/.aws ]]; then
-    if [[ -f $HOME/.aws ]]; then
-        rm -rf $HOME/.aws
+if [[ $aws == 1 ]]; then
+    if ! [[ -L $HOME/.aws ]]; then
+        if [[ -f $HOME/.aws ]]; then
+            rm -rf $HOME/.aws
+        fi
+        ln -s $AWS_VOLUME $HOME/.aws
     fi
-    ln -s $AWS_VOLUME $HOME/.aws
 fi
-if ! [[ -L $HOME/.ssh ]]; then
-    if [[ -f $HOME/.ssh ]]; then
-        rm -rf $HOME/.ssh
+
+if [[ $ssh == 1 ]]; then
+    if ! [[ -L $HOME/.ssh ]]; then
+        if [[ -f $HOME/.ssh ]]; then
+            rm -rf $HOME/.ssh
+        fi
+        ln -s $SSH_VOLUME $HOME/.ssh
     fi
-    ln -s $SSH_VOLUME $HOME/.ssh
 fi
-if ! [[ -L $HOME/.gitconfig ]]; then
-    if [[ -f $HOME/.gitconfig ]]; then
-        rm -f $HOME/.gitconfig
+
+if [[ $git == 1 ]]; then
+    if ! [[ -L $HOME/.gitconfig ]]; then
+        if [[ -f $HOME/.gitconfig ]]; then
+            rm -f $HOME/.gitconfig
+        fi
+        ln -s $GIT_VOLUME/gitconfig $HOME/.gitconfig
     fi
-    ln -s $GIT_VOLUME/gitconfig $HOME/.gitconfig
 fi
